# Generated by Django 2.0.2 on 2018-03-04 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.TextField()),
                ('probability_of_classification', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='FoodPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('tags', models.ManyToManyField(to='api.FoodClassification')),
            ],
        ),
        migrations.CreateModel(
            name='FoodPreferenceElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_preference_sum', models.FloatField()),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.FoodClassification')),
            ],
        ),
        migrations.CreateModel(
            name='UserFoodProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('food_pictures_hated', models.ManyToManyField(related_name='user_hates', to='api.FoodPicture')),
                ('food_pictures_liked', models.ManyToManyField(related_name='user_likes', to='api.FoodPicture')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='foodpreferenceelement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.UserFoodProfile'),
        ),
        migrations.AlterUniqueTogether(
            name='foodpreferenceelement',
            unique_together={('user', 'classification')},
        ),
    ]
